# Generated by Django 3.0.3 on 2020-05-18 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200518_2105'),
        ('product', '0007_auto_20200518_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userprofile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.UserProfile'),
            preserve_default=False,
        ),
    ]
