# Generated by Django 3.0.3 on 2020-05-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200518_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='telefon',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
